///draw_text_shadow_transformed(x, y, string, shadow_size, shadow_colour, text_colour, xscale, yscale, rotation);
var _x, _y, _string, _shadow_size, shadow_colour, text_colour, _xscale, _yscale, _rotation;
_x = argument[0];
_y = argument[1];
_string = argument[2];
_shadow_size = argument[3];
_shadow_colour = argument[4];
_text_colour = argument[5];
_xscale = argument[6];
_yscale = argument[7];
_rotation = argument[8];
draw_set_colour(_shadow_colour);
draw_text_transformed((_x + _shadow_size), (_y + _shadow_size), string(_string), _xscale, _yscale, _rotation);
draw_set_colour(_text_colour);
draw_text_transformed(_x, _y, string(_string), _xscale, _yscale, _rotation);
